# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexis/EPITECH[02]/OOP_indie_studio_2019

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexis/EPITECH[02]/OOP_indie_studio_2019

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexis/EPITECH[02]/OOP_indie_studio_2019/CMakeFiles /home/alexis/EPITECH[02]/OOP_indie_studio_2019/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexis/EPITECH[02]/OOP_indie_studio_2019/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

Code/main.o: Code/main.cpp.o

.PHONY : Code/main.o

# target to build an object file
Code/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/main.cpp.o
.PHONY : Code/main.cpp.o

Code/main.i: Code/main.cpp.i

.PHONY : Code/main.i

# target to preprocess a source file
Code/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/main.cpp.i
.PHONY : Code/main.cpp.i

Code/main.s: Code/main.cpp.s

.PHONY : Code/main.s

# target to generate assembly for a file
Code/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/main.cpp.s
.PHONY : Code/main.cpp.s

Code/src/Display/Buttons.o: Code/src/Display/Buttons.cpp.o

.PHONY : Code/src/Display/Buttons.o

# target to build an object file
Code/src/Display/Buttons.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Display/Buttons.cpp.o
.PHONY : Code/src/Display/Buttons.cpp.o

Code/src/Display/Buttons.i: Code/src/Display/Buttons.cpp.i

.PHONY : Code/src/Display/Buttons.i

# target to preprocess a source file
Code/src/Display/Buttons.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Display/Buttons.cpp.i
.PHONY : Code/src/Display/Buttons.cpp.i

Code/src/Display/Buttons.s: Code/src/Display/Buttons.cpp.s

.PHONY : Code/src/Display/Buttons.s

# target to generate assembly for a file
Code/src/Display/Buttons.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Display/Buttons.cpp.s
.PHONY : Code/src/Display/Buttons.cpp.s

Code/src/Display/Display.o: Code/src/Display/Display.cpp.o

.PHONY : Code/src/Display/Display.o

# target to build an object file
Code/src/Display/Display.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Display/Display.cpp.o
.PHONY : Code/src/Display/Display.cpp.o

Code/src/Display/Display.i: Code/src/Display/Display.cpp.i

.PHONY : Code/src/Display/Display.i

# target to preprocess a source file
Code/src/Display/Display.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Display/Display.cpp.i
.PHONY : Code/src/Display/Display.cpp.i

Code/src/Display/Display.s: Code/src/Display/Display.cpp.s

.PHONY : Code/src/Display/Display.s

# target to generate assembly for a file
Code/src/Display/Display.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Display/Display.cpp.s
.PHONY : Code/src/Display/Display.cpp.s

Code/src/Game/Game.o: Code/src/Game/Game.cpp.o

.PHONY : Code/src/Game/Game.o

# target to build an object file
Code/src/Game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/Game.cpp.o
.PHONY : Code/src/Game/Game.cpp.o

Code/src/Game/Game.i: Code/src/Game/Game.cpp.i

.PHONY : Code/src/Game/Game.i

# target to preprocess a source file
Code/src/Game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/Game.cpp.i
.PHONY : Code/src/Game/Game.cpp.i

Code/src/Game/Game.s: Code/src/Game/Game.cpp.s

.PHONY : Code/src/Game/Game.s

# target to generate assembly for a file
Code/src/Game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/Game.cpp.s
.PHONY : Code/src/Game/Game.cpp.s

Code/src/Game/GameObjects/Bomb/Bomb.o: Code/src/Game/GameObjects/Bomb/Bomb.cpp.o

.PHONY : Code/src/Game/GameObjects/Bomb/Bomb.o

# target to build an object file
Code/src/Game/GameObjects/Bomb/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Bomb/Bomb.cpp.o
.PHONY : Code/src/Game/GameObjects/Bomb/Bomb.cpp.o

Code/src/Game/GameObjects/Bomb/Bomb.i: Code/src/Game/GameObjects/Bomb/Bomb.cpp.i

.PHONY : Code/src/Game/GameObjects/Bomb/Bomb.i

# target to preprocess a source file
Code/src/Game/GameObjects/Bomb/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Bomb/Bomb.cpp.i
.PHONY : Code/src/Game/GameObjects/Bomb/Bomb.cpp.i

Code/src/Game/GameObjects/Bomb/Bomb.s: Code/src/Game/GameObjects/Bomb/Bomb.cpp.s

.PHONY : Code/src/Game/GameObjects/Bomb/Bomb.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Bomb/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Bomb/Bomb.cpp.s
.PHONY : Code/src/Game/GameObjects/Bomb/Bomb.cpp.s

Code/src/Game/GameObjects/Bomb/Fireball/Fireball.o: Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.o

.PHONY : Code/src/Game/GameObjects/Bomb/Fireball/Fireball.o

# target to build an object file
Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.o
.PHONY : Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.o

Code/src/Game/GameObjects/Bomb/Fireball/Fireball.i: Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.i

.PHONY : Code/src/Game/GameObjects/Bomb/Fireball/Fireball.i

# target to preprocess a source file
Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.i
.PHONY : Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.i

Code/src/Game/GameObjects/Bomb/Fireball/Fireball.s: Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.s

.PHONY : Code/src/Game/GameObjects/Bomb/Fireball/Fireball.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.s
.PHONY : Code/src/Game/GameObjects/Bomb/Fireball/Fireball.cpp.s

Code/src/Game/GameObjects/Bomberman/Bomberman.o: Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.o

.PHONY : Code/src/Game/GameObjects/Bomberman/Bomberman.o

# target to build an object file
Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.o
.PHONY : Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.o

Code/src/Game/GameObjects/Bomberman/Bomberman.i: Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.i

.PHONY : Code/src/Game/GameObjects/Bomberman/Bomberman.i

# target to preprocess a source file
Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.i
.PHONY : Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.i

Code/src/Game/GameObjects/Bomberman/Bomberman.s: Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.s

.PHONY : Code/src/Game/GameObjects/Bomberman/Bomberman.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.s
.PHONY : Code/src/Game/GameObjects/Bomberman/Bomberman.cpp.s

Code/src/Game/GameObjects/BombermanIA/BombermanIA.o: Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.o

.PHONY : Code/src/Game/GameObjects/BombermanIA/BombermanIA.o

# target to build an object file
Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.o
.PHONY : Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.o

Code/src/Game/GameObjects/BombermanIA/BombermanIA.i: Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.i

.PHONY : Code/src/Game/GameObjects/BombermanIA/BombermanIA.i

# target to preprocess a source file
Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.i
.PHONY : Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.i

Code/src/Game/GameObjects/BombermanIA/BombermanIA.s: Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.s

.PHONY : Code/src/Game/GameObjects/BombermanIA/BombermanIA.s

# target to generate assembly for a file
Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.s
.PHONY : Code/src/Game/GameObjects/BombermanIA/BombermanIA.cpp.s

Code/src/Game/GameObjects/Camera/Camera.o: Code/src/Game/GameObjects/Camera/Camera.cpp.o

.PHONY : Code/src/Game/GameObjects/Camera/Camera.o

# target to build an object file
Code/src/Game/GameObjects/Camera/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Camera/Camera.cpp.o
.PHONY : Code/src/Game/GameObjects/Camera/Camera.cpp.o

Code/src/Game/GameObjects/Camera/Camera.i: Code/src/Game/GameObjects/Camera/Camera.cpp.i

.PHONY : Code/src/Game/GameObjects/Camera/Camera.i

# target to preprocess a source file
Code/src/Game/GameObjects/Camera/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Camera/Camera.cpp.i
.PHONY : Code/src/Game/GameObjects/Camera/Camera.cpp.i

Code/src/Game/GameObjects/Camera/Camera.s: Code/src/Game/GameObjects/Camera/Camera.cpp.s

.PHONY : Code/src/Game/GameObjects/Camera/Camera.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Camera/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Camera/Camera.cpp.s
.PHONY : Code/src/Game/GameObjects/Camera/Camera.cpp.s

Code/src/Game/GameObjects/GameObjects.o: Code/src/Game/GameObjects/GameObjects.cpp.o

.PHONY : Code/src/Game/GameObjects/GameObjects.o

# target to build an object file
Code/src/Game/GameObjects/GameObjects.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/GameObjects.cpp.o
.PHONY : Code/src/Game/GameObjects/GameObjects.cpp.o

Code/src/Game/GameObjects/GameObjects.i: Code/src/Game/GameObjects/GameObjects.cpp.i

.PHONY : Code/src/Game/GameObjects/GameObjects.i

# target to preprocess a source file
Code/src/Game/GameObjects/GameObjects.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/GameObjects.cpp.i
.PHONY : Code/src/Game/GameObjects/GameObjects.cpp.i

Code/src/Game/GameObjects/GameObjects.s: Code/src/Game/GameObjects/GameObjects.cpp.s

.PHONY : Code/src/Game/GameObjects/GameObjects.s

# target to generate assembly for a file
Code/src/Game/GameObjects/GameObjects.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/GameObjects.cpp.s
.PHONY : Code/src/Game/GameObjects/GameObjects.cpp.s

Code/src/Game/GameObjects/Map/BombUp/BombUp.o: Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.o

.PHONY : Code/src/Game/GameObjects/Map/BombUp/BombUp.o

# target to build an object file
Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.o
.PHONY : Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.o

Code/src/Game/GameObjects/Map/BombUp/BombUp.i: Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.i

.PHONY : Code/src/Game/GameObjects/Map/BombUp/BombUp.i

# target to preprocess a source file
Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.i
.PHONY : Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.i

Code/src/Game/GameObjects/Map/BombUp/BombUp.s: Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.s

.PHONY : Code/src/Game/GameObjects/Map/BombUp/BombUp.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.s
.PHONY : Code/src/Game/GameObjects/Map/BombUp/BombUp.cpp.s

Code/src/Game/GameObjects/Map/DBlock/DBlock.o: Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.o

.PHONY : Code/src/Game/GameObjects/Map/DBlock/DBlock.o

# target to build an object file
Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.o
.PHONY : Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.o

Code/src/Game/GameObjects/Map/DBlock/DBlock.i: Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.i

.PHONY : Code/src/Game/GameObjects/Map/DBlock/DBlock.i

# target to preprocess a source file
Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.i
.PHONY : Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.i

Code/src/Game/GameObjects/Map/DBlock/DBlock.s: Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.s

.PHONY : Code/src/Game/GameObjects/Map/DBlock/DBlock.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.s
.PHONY : Code/src/Game/GameObjects/Map/DBlock/DBlock.cpp.s

Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.o: Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.o

.PHONY : Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.o

# target to build an object file
Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.o
.PHONY : Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.o

Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.i: Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.i

.PHONY : Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.i

# target to preprocess a source file
Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.i
.PHONY : Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.i

Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.s: Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.s

.PHONY : Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.s
.PHONY : Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.cpp.s

Code/src/Game/GameObjects/Map/FireUp/FireUp.o: Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.o

.PHONY : Code/src/Game/GameObjects/Map/FireUp/FireUp.o

# target to build an object file
Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.o
.PHONY : Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.o

Code/src/Game/GameObjects/Map/FireUp/FireUp.i: Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.i

.PHONY : Code/src/Game/GameObjects/Map/FireUp/FireUp.i

# target to preprocess a source file
Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.i
.PHONY : Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.i

Code/src/Game/GameObjects/Map/FireUp/FireUp.s: Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.s

.PHONY : Code/src/Game/GameObjects/Map/FireUp/FireUp.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.s
.PHONY : Code/src/Game/GameObjects/Map/FireUp/FireUp.cpp.s

Code/src/Game/GameObjects/Map/Floor/Floor.o: Code/src/Game/GameObjects/Map/Floor/Floor.cpp.o

.PHONY : Code/src/Game/GameObjects/Map/Floor/Floor.o

# target to build an object file
Code/src/Game/GameObjects/Map/Floor/Floor.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/Floor/Floor.cpp.o
.PHONY : Code/src/Game/GameObjects/Map/Floor/Floor.cpp.o

Code/src/Game/GameObjects/Map/Floor/Floor.i: Code/src/Game/GameObjects/Map/Floor/Floor.cpp.i

.PHONY : Code/src/Game/GameObjects/Map/Floor/Floor.i

# target to preprocess a source file
Code/src/Game/GameObjects/Map/Floor/Floor.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/Floor/Floor.cpp.i
.PHONY : Code/src/Game/GameObjects/Map/Floor/Floor.cpp.i

Code/src/Game/GameObjects/Map/Floor/Floor.s: Code/src/Game/GameObjects/Map/Floor/Floor.cpp.s

.PHONY : Code/src/Game/GameObjects/Map/Floor/Floor.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Map/Floor/Floor.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/Floor/Floor.cpp.s
.PHONY : Code/src/Game/GameObjects/Map/Floor/Floor.cpp.s

Code/src/Game/GameObjects/Map/Map.o: Code/src/Game/GameObjects/Map/Map.cpp.o

.PHONY : Code/src/Game/GameObjects/Map/Map.o

# target to build an object file
Code/src/Game/GameObjects/Map/Map.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/Map.cpp.o
.PHONY : Code/src/Game/GameObjects/Map/Map.cpp.o

Code/src/Game/GameObjects/Map/Map.i: Code/src/Game/GameObjects/Map/Map.cpp.i

.PHONY : Code/src/Game/GameObjects/Map/Map.i

# target to preprocess a source file
Code/src/Game/GameObjects/Map/Map.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/Map.cpp.i
.PHONY : Code/src/Game/GameObjects/Map/Map.cpp.i

Code/src/Game/GameObjects/Map/Map.s: Code/src/Game/GameObjects/Map/Map.cpp.s

.PHONY : Code/src/Game/GameObjects/Map/Map.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Map/Map.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/Map.cpp.s
.PHONY : Code/src/Game/GameObjects/Map/Map.cpp.s

Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.o: Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.o

.PHONY : Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.o

# target to build an object file
Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.o
.PHONY : Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.o

Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.i: Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.i

.PHONY : Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.i

# target to preprocess a source file
Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.i
.PHONY : Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.i

Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.s: Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.s

.PHONY : Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.s
.PHONY : Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.cpp.s

Code/src/Game/GameObjects/Map/Wall/Wall.o: Code/src/Game/GameObjects/Map/Wall/Wall.cpp.o

.PHONY : Code/src/Game/GameObjects/Map/Wall/Wall.o

# target to build an object file
Code/src/Game/GameObjects/Map/Wall/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/Wall/Wall.cpp.o
.PHONY : Code/src/Game/GameObjects/Map/Wall/Wall.cpp.o

Code/src/Game/GameObjects/Map/Wall/Wall.i: Code/src/Game/GameObjects/Map/Wall/Wall.cpp.i

.PHONY : Code/src/Game/GameObjects/Map/Wall/Wall.i

# target to preprocess a source file
Code/src/Game/GameObjects/Map/Wall/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/Wall/Wall.cpp.i
.PHONY : Code/src/Game/GameObjects/Map/Wall/Wall.cpp.i

Code/src/Game/GameObjects/Map/Wall/Wall.s: Code/src/Game/GameObjects/Map/Wall/Wall.cpp.s

.PHONY : Code/src/Game/GameObjects/Map/Wall/Wall.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Map/Wall/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/Wall/Wall.cpp.s
.PHONY : Code/src/Game/GameObjects/Map/Wall/Wall.cpp.s

Code/src/Game/GameObjects/Map/WallPass/WallPass.o: Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.o

.PHONY : Code/src/Game/GameObjects/Map/WallPass/WallPass.o

# target to build an object file
Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.o
.PHONY : Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.o

Code/src/Game/GameObjects/Map/WallPass/WallPass.i: Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.i

.PHONY : Code/src/Game/GameObjects/Map/WallPass/WallPass.i

# target to preprocess a source file
Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.i
.PHONY : Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.i

Code/src/Game/GameObjects/Map/WallPass/WallPass.s: Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.s

.PHONY : Code/src/Game/GameObjects/Map/WallPass/WallPass.s

# target to generate assembly for a file
Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.s
.PHONY : Code/src/Game/GameObjects/Map/WallPass/WallPass.cpp.s

Code/src/Game/Music.o: Code/src/Game/Music.cpp.o

.PHONY : Code/src/Game/Music.o

# target to build an object file
Code/src/Game/Music.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/Music.cpp.o
.PHONY : Code/src/Game/Music.cpp.o

Code/src/Game/Music.i: Code/src/Game/Music.cpp.i

.PHONY : Code/src/Game/Music.i

# target to preprocess a source file
Code/src/Game/Music.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/Music.cpp.i
.PHONY : Code/src/Game/Music.cpp.i

Code/src/Game/Music.s: Code/src/Game/Music.cpp.s

.PHONY : Code/src/Game/Music.s

# target to generate assembly for a file
Code/src/Game/Music.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Game/Music.cpp.s
.PHONY : Code/src/Game/Music.cpp.s

Code/src/Libs/Irrlicht/Irrlicht.o: Code/src/Libs/Irrlicht/Irrlicht.cpp.o

.PHONY : Code/src/Libs/Irrlicht/Irrlicht.o

# target to build an object file
Code/src/Libs/Irrlicht/Irrlicht.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Libs/Irrlicht/Irrlicht.cpp.o
.PHONY : Code/src/Libs/Irrlicht/Irrlicht.cpp.o

Code/src/Libs/Irrlicht/Irrlicht.i: Code/src/Libs/Irrlicht/Irrlicht.cpp.i

.PHONY : Code/src/Libs/Irrlicht/Irrlicht.i

# target to preprocess a source file
Code/src/Libs/Irrlicht/Irrlicht.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Libs/Irrlicht/Irrlicht.cpp.i
.PHONY : Code/src/Libs/Irrlicht/Irrlicht.cpp.i

Code/src/Libs/Irrlicht/Irrlicht.s: Code/src/Libs/Irrlicht/Irrlicht.cpp.s

.PHONY : Code/src/Libs/Irrlicht/Irrlicht.s

# target to generate assembly for a file
Code/src/Libs/Irrlicht/Irrlicht.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Code/src/Libs/Irrlicht/Irrlicht.cpp.s
.PHONY : Code/src/Libs/Irrlicht/Irrlicht.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... edit_cache"
	@echo "... Code/main.o"
	@echo "... Code/main.i"
	@echo "... Code/main.s"
	@echo "... Code/src/Display/Buttons.o"
	@echo "... Code/src/Display/Buttons.i"
	@echo "... Code/src/Display/Buttons.s"
	@echo "... Code/src/Display/Display.o"
	@echo "... Code/src/Display/Display.i"
	@echo "... Code/src/Display/Display.s"
	@echo "... Code/src/Game/Game.o"
	@echo "... Code/src/Game/Game.i"
	@echo "... Code/src/Game/Game.s"
	@echo "... Code/src/Game/GameObjects/Bomb/Bomb.o"
	@echo "... Code/src/Game/GameObjects/Bomb/Bomb.i"
	@echo "... Code/src/Game/GameObjects/Bomb/Bomb.s"
	@echo "... Code/src/Game/GameObjects/Bomb/Fireball/Fireball.o"
	@echo "... Code/src/Game/GameObjects/Bomb/Fireball/Fireball.i"
	@echo "... Code/src/Game/GameObjects/Bomb/Fireball/Fireball.s"
	@echo "... Code/src/Game/GameObjects/Bomberman/Bomberman.o"
	@echo "... Code/src/Game/GameObjects/Bomberman/Bomberman.i"
	@echo "... Code/src/Game/GameObjects/Bomberman/Bomberman.s"
	@echo "... Code/src/Game/GameObjects/BombermanIA/BombermanIA.o"
	@echo "... Code/src/Game/GameObjects/BombermanIA/BombermanIA.i"
	@echo "... Code/src/Game/GameObjects/BombermanIA/BombermanIA.s"
	@echo "... Code/src/Game/GameObjects/Camera/Camera.o"
	@echo "... Code/src/Game/GameObjects/Camera/Camera.i"
	@echo "... Code/src/Game/GameObjects/Camera/Camera.s"
	@echo "... Code/src/Game/GameObjects/GameObjects.o"
	@echo "... Code/src/Game/GameObjects/GameObjects.i"
	@echo "... Code/src/Game/GameObjects/GameObjects.s"
	@echo "... Code/src/Game/GameObjects/Map/BombUp/BombUp.o"
	@echo "... Code/src/Game/GameObjects/Map/BombUp/BombUp.i"
	@echo "... Code/src/Game/GameObjects/Map/BombUp/BombUp.s"
	@echo "... Code/src/Game/GameObjects/Map/DBlock/DBlock.o"
	@echo "... Code/src/Game/GameObjects/Map/DBlock/DBlock.i"
	@echo "... Code/src/Game/GameObjects/Map/DBlock/DBlock.s"
	@echo "... Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.o"
	@echo "... Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.i"
	@echo "... Code/src/Game/GameObjects/Map/EmptyBlock/EmptyBlock.s"
	@echo "... Code/src/Game/GameObjects/Map/FireUp/FireUp.o"
	@echo "... Code/src/Game/GameObjects/Map/FireUp/FireUp.i"
	@echo "... Code/src/Game/GameObjects/Map/FireUp/FireUp.s"
	@echo "... Code/src/Game/GameObjects/Map/Floor/Floor.o"
	@echo "... Code/src/Game/GameObjects/Map/Floor/Floor.i"
	@echo "... Code/src/Game/GameObjects/Map/Floor/Floor.s"
	@echo "... Code/src/Game/GameObjects/Map/Map.o"
	@echo "... Code/src/Game/GameObjects/Map/Map.i"
	@echo "... Code/src/Game/GameObjects/Map/Map.s"
	@echo "... Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.o"
	@echo "... Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.i"
	@echo "... Code/src/Game/GameObjects/Map/SpeedUp/SpeedUp.s"
	@echo "... Code/src/Game/GameObjects/Map/Wall/Wall.o"
	@echo "... Code/src/Game/GameObjects/Map/Wall/Wall.i"
	@echo "... Code/src/Game/GameObjects/Map/Wall/Wall.s"
	@echo "... Code/src/Game/GameObjects/Map/WallPass/WallPass.o"
	@echo "... Code/src/Game/GameObjects/Map/WallPass/WallPass.i"
	@echo "... Code/src/Game/GameObjects/Map/WallPass/WallPass.s"
	@echo "... Code/src/Game/Music.o"
	@echo "... Code/src/Game/Music.i"
	@echo "... Code/src/Game/Music.s"
	@echo "... Code/src/Libs/Irrlicht/Irrlicht.o"
	@echo "... Code/src/Libs/Irrlicht/Irrlicht.i"
	@echo "... Code/src/Libs/Irrlicht/Irrlicht.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

